#!/bin/zsh
export skip_global_compinit=1

SOURCE=${(%):-%N}
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DOTFILES_DIR="$( cd -P "$( dirname "$SOURCE" )"/../.. && pwd )"

export ZDOTDIR="${DOTFILES_DIR}"
rsz() {
	if [[ -t 0 && $# -eq 0 ]];then
		local IFS='[;' geometry x y
		print -n '\e7\e[r\e[999;999H\e[6n\e8'
		read -r -sd _ _ geometry
		x=${geometry##*;} y=${geometry%%;*}
		if [[ ${COLUMNS} -eq ${x} && ${LINES} -eq ${y} ]];then
			print "${TERM} ${x}x${y}"
		else
			#print "${COLUMNS}x${LINES} -> ${x}x${y}"
			stty cols "${x}" rows "${y}"
		fi
	fi
}
# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ -z $SSH_CLIENT && -z $TERM_PROGRAM ]]; then
  rsz "$@"
fi
ulimit -c unlimited
